export JAVA_HOME="$(/usr/libexec/java_home)"
export EC2_HOME="/opt/boxen/homebrew/Library/LinkedKegs/ec2-api-tools/jars"
export AWS_ELB_HOME="/opt/boxen/homebrew/Library/LinkedKegs/elb-tools/jars"
# export EC2_PRIVATE_KEY="$(/bin/ls "$HOME"/.ec2/pk-*.pem | /usr/bin/head -1)"
# export EC2_CERT="$(/bin/ls "$HOME"/.ec2/cert-*.pem | /usr/bin/head -1)"
